#define XMLGUI_DISTRIBUTION_TEXT "${XMLGUI_DISTRIBUTION_TEXT}"
#define XMLGUI_COMPILING_OS "${CMAKE_SYSTEM_NAME}"

#define CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}"
#define KDE_INSTALL_LIBEXECDIR_KF5 "${KDE_INSTALL_LIBEXECDIR_KF5}"

/* KF5GlobalAccel available */
#cmakedefine01 HAVE_GLOBALACCEL
