// DO NOT EDIT - EDIT products in bugs.kde.org and run ./make_kdepackages_updated.py in kxmlgui to update
const char * const packages[] = {
    "abakus",
    "Active",
    "Active/Application launcher",
    "Active/Applications",
    "Active/Contour activity screen",
    "Active/Contour activity switcher",
    "Active/Contour recommendations manager",
    "Active/General",
    "Active/Keyboard",
    "Active/Plasma mobile shell",
    "Active/Share Like Connect",
    "Active/Task switcher",
    "Active/Top Bar",
    "Active/Widgets strip containment",
    "aki",
    "aki/libakicore",
    "akiirc",
    "akiirc/ChannelView",
    "akiirc/ChatInput",
    "akiirc/notifications",
    "akiirc/ServerView",
    "Akonadi",
    "Akonadi/Account Wizard",
    "Akonadi/akonadiconsole",
    "Akonadi/Archive Mail Agent",
    "Akonadi/Baloo Indexer",
    "Akonadi/Birthdays Resource",
    "Akonadi/Contacts resource",
    "Akonadi/DAV Resource",
    "Akonadi/Facebook Resource",
    "Akonadi/Gmail resource",
    "Akonadi/Google Resource",
    "Akonadi/GoogleData Resource",
    "Akonadi/ICal file resource",
    "Akonadi/IMAP resource",
    "Akonadi/KAlarm resource",
    "Akonadi/Knut resource",
    "Akonadi/Kolab Resource",
    "Akonadi/KResource compat bridges",
    "Akonadi/libakonadi",
    "Akonadi/Local Bookmark Resource",
    "Akonadi/Mail Dispatcher Agent",
    "Akonadi/Mail Filter Agent",
    "Akonadi/Maildir Resource",
    "Akonadi/MBox Resource",
    "Akonadi/Migration",
    "Akonadi/Mixed Maildir resource",
    "Akonadi/Nepomuk Feeder Agents",
    "Akonadi/New Mail Notifier",
    "Akonadi/OpenXchange Resource",
    "Akonadi/POP3 Resource",
    "Akonadi/SendLaterAgent",
    "Akonadi/server",
    "Akonadi/SingleFileResourceBase",
    "Akonadi/Tag Resource",
    "Akonadi/VCard dir resource",
    "Akonadi/VCard file resource",
    "akregator",
    "akregator/akonadi-port",
    "akregator/akregator konqueror plugin",
    "akregator/feed parser",
    "akregator/internal browser",
    "akregator/kontact plugin",
    "akregator/metakit plugin",
    "akunambol",
    "akunambol/syncronization",
    "amarok",
    "amarok/Collection Browser",
    "amarok/Collections/CD",
    "amarok/Collections/DAAP",
    "amarok/Collections/iPod iPhone",
    "amarok/Collections/Local",
    "amarok/Collections/Media Devices",
    "amarok/Collections/MTP player",
    "amarok/Collections/Nepomuk",
    "amarok/Collections/Organize Files Dialog",
    "amarok/Collections/Spotify",
    "amarok/Collections/UPnP",
    "amarok/Collections/USB mass storage and MSC",
    "amarok/Context View",
    "amarok/Context View/Albums",
    "amarok/Context View/Cover Bling",
    "amarok/Context View/Covergrid",
    "amarok/Context View/Current Track",
    "amarok/Context View/Info",
    "amarok/Context View/Labels",
    "amarok/Context View/Lyrics",
    "amarok/Context View/Photos",
    "amarok/Context View/Similar Artists",
    "amarok/Context View/Spectrum Analyzer",
    "amarok/Context View/Tabs",
    "amarok/Context View/Upcoming Events",
    "amarok/Context View/Video",
    "amarok/Context View/Wikipedia",
    "amarok/D-Bus interfaces",
    "amarok/Documentation",
    "amarok/File Browser",
    "amarok/Internet Services",
    "amarok/LikeBack",
    "amarok/Metadata Editing and Reading",
    "amarok/Moodbar",
    "amarok/Notifications",
    "amarok/Playback",
    "amarok/Playback/CUE sheet support",
    "amarok/Playback/Replay Gain",
    "amarok/Playback/Streams",
    "amarok/Playlist",
    "amarok/Playlist/Playlist Layout Editor",
    "amarok/Playlists/Automated Playlist Generator",
    "amarok/Playlists/Dynamic Playlists",
    "amarok/Playlists/Saved Playlists",
    "amarok/Podcast",
    "amarok/PopUpDropper",
    "amarok/Services/Amazon MP3 Store",
    "amarok/Services/Ampache",
    "amarok/Services/gpodder.net",
    "amarok/Services/Jamendo",
    "amarok/Services/Last.fm",
    "amarok/Services/Magnatune",
    "amarok/Services/MP3tunes",
    "amarok/Services/Podcast Directory",
    "amarok/Shortcuts",
    "amarok/Toolbar",
    "amarok/Tools/Bookmark Manager",
    "amarok/Tools/Cover Manager",
    "amarok/Tools/Equalizer",
    "amarok/Tools/Network Requests Viewer",
    "amarok/Tools/Script Manager",
    "amarok/Tools/Statistics Synchronization",
    "amarok/Transcoding",
    "amor",
    "analitza",
    "analitza/analitzaplot",
    "analitza/core",
    "apper",
    "ark",
    "Artikulate",
    "Artikulate/course files",
    "Artikulate/language specifications",
    "artwork",
    "attica",
    "AVKode",
    "AVKode/AVKode library",
    "Baloo",
    "Baloo/Files",
    "Baloo/General",
    "Baloo/KCM",
    "Baloo/Tags",
    "Baloo/Timeline",
    "Baloo/Widgets",
    "bangarang",
    "bangarang/Baloo",
    "bangarang/UI",
    "basket",
    "bindings",
    "bindings/pykde",
    "blinken",
    "blogilo",
    "Bluedevil",
    "Bluedevil/daemon",
    "Bluedevil/kcm",
    "Bluedevil/kio-bt",
    "Bluedevil/kio-obex",
    "Bluedevil/libbluedevil",
    "Bluedevil/system tray",
    "Bluedevil/wizard",
    "bodega",
    "bodega/Client library",
    "bodega/Manager",
    "bodega/Plasma Active client",
    "bodega/Server",
    "bodega/Web client",
    "bomber",
    "bovo",
    "braindump",
    "braindump/application",
    "Breeze",
    "Breeze/Icons",
    "Breeze/QStyle",
    "Breeze/QtQuickControls",
    "Breeze/window decoration",
    "bugs.kde.org",
    "bugs.kde.org/code customizations",
    "bugs.kde.org/database",
    "bugs.kde.org/product/component changes",
    "bugs.kde.org/templates",
    "buildsystem",
    "buildsystem/KDE3 (autotools)",
    "buildsystem/KDE4 (cmake)",
    "calligraactive",
    "calligraactive/usability",
    "calligraauthor",
    "calligrachart",
    "calligrachart/3D charts",
    "calligrachart/opendocument",
    "calligrachart/usability",
    "calligracommon",
    "calligracommon/embedded-documents",
    "calligracommon/filters",
    "calligracommon/flake",
    "calligracommon/flake-picture",
    "calligracommon/flake-plugins",
    "calligracommon/koreport",
    "calligracommon/path-shapes",
    "calligracommon/pigment",
    "calligracommon/text-layout",
    "calligracommon/text-tool",
    "calligracommon/text-tool-plugins",
    "calligracommon/usability",
    "calligraflow",
    "calligraflow/opendocument",
    "calligraflow/usability",
    "calligraformula",
    "calligraformula/filters",
    "calligraformula/usability",
    "calligragemini",
    "calligraplan",
    "calligraplan/usability",
    "calligraplan/work",
    "calligraservices",
    "calligraservices/Build Server",
    "calligraservices/quality.calligra-suite.org",
    "calligraservices/www.calligra-suite.org",
    "calligrasheets",
    "calligrasheets/filter/xls",
    "calligrasheets/filter/xlsx",
    "calligrasheets/filters",
    "calligrasheets/functions",
    "calligrasheets/opendocument",
    "calligrasheets/shape",
    "calligrasheets/usability",
    "calligrastage",
    "calligrastage/filter/ppt",
    "calligrastage/filter/pptx",
    "calligrastage/filters",
    "calligrastage/okularplugin",
    "calligrastage/opendocument",
    "calligrastage/usability",
    "calligrawords",
    "calligrawords/doc",
    "calligrawords/docx",
    "calligrawords/filters",
    "calligrawords/okularplugin",
    "calligrawords/opendocument",
    "calligrawords/review tool",
    "calligrawords/tables",
    "calligrawords/usability",
    "cantor",
    "cantor/kalgebra-backend",
    "cantor/maxima-backend",
    "cantor/octave-backend",
    "cantor/python2-backend",
    "cantor/qualculate-backend",
    "cantor/r-backend",
    "cantor/sage-backend",
    "cantor/scilab-backend",
    "cervisia",
    "choqok",
    "choqok/Gnu social (StatusNet)",
    "choqok/OCS",
    "choqok/Pump.io",
    "choqok/Twitter",
    "cirkuit",
    "cocoon",
    "colibri",
    "colord-kde",
    "colord-kde/Daemon Module (KDED)",
    "colord-kde/Systems Settings Module (KCM)",
    "conquirere",
    "datakiosk",
    "dekorator",
    "dekorator/kcm part",
    "digikam",
    "digikam/Advanced Rename",
    "digikam/Albums GUI",
    "digikam/Baloo Interface",
    "digikam/Batch Queue Manager",
    "digikam/Color Management",
    "digikam/Database",
    "digikam/Dates",
    "digikam/Documentation",
    "digikam/Export",
    "digikam/Face Management",
    "digikam/Filters",
    "digikam/Fuzzy Searches",
    "digikam/Geolocation",
    "digikam/Image Editor",
    "digikam/Import",
    "digikam/Kioslave",
    "digikam/Kipiinterface",
    "digikam/Labels",
    "digikam/libkdcraw",
    "digikam/libkexiv2",
    "digikam/libkface",
    "digikam/libkgeomap",
    "digikam/libkipi",
    "digikam/Light Table",
    "digikam/Maintenance",
    "digikam/Map Searches",
    "digikam/Metadata",
    "digikam/Portability",
    "digikam/Preview",
    "digikam/Progress Manager",
    "digikam/RAW files management",
    "digikam/Searches",
    "digikam/setup",
    "digikam/Sidecar Management",
    "digikam/SlideShow",
    "digikam/TableView",
    "digikam/Tags",
    "digikam/Thumbnails",
    "digikam/Time Line",
    "digikam/Usability",
    "digikam/Versioning",
    "digikam/Workflow",
    "digikamimageplugins",
    "digikamimageplugins/Adjust Curves",
    "digikamimageplugins/AdjustLevels",
    "digikamimageplugins/Anti-Vignetting",
    "digikamimageplugins/Aspect Ratio Crop",
    "digikamimageplugins/Auto-Colors",
    "digikamimageplugins/BCG correction",
    "digikamimageplugins/Black and White",
    "digikamimageplugins/Blur",
    "digikamimageplugins/Blur Fx",
    "digikamimageplugins/Border",
    "digikamimageplugins/Channel Mixer",
    "digikamimageplugins/Charcoal",
    "digikamimageplugins/Color Balance",
    "digikamimageplugins/Color Management",
    "digikamimageplugins/ColorFx",
    "digikamimageplugins/Distortion Fx",
    "digikamimageplugins/Emboss",
    "digikamimageplugins/Filmgrain",
    "digikamimageplugins/Free Rotation",
    "digikamimageplugins/Hot Pixels",
    "digikamimageplugins/HSL Correction",
    "digikamimageplugins/Inpainting",
    "digikamimageplugins/Insert Text",
    "digikamimageplugins/Lens Distortion",
    "digikamimageplugins/Liquid Rescale",
    "digikamimageplugins/Local Contrast",
    "digikamimageplugins/Noise Reduction",
    "digikamimageplugins/OilPaint",
    "digikamimageplugins/Perspective",
    "digikamimageplugins/Raindrops",
    "digikamimageplugins/Red Eyes",
    "digikamimageplugins/Refocus",
    "digikamimageplugins/Resize",
    "digikamimageplugins/Restoration",
    "digikamimageplugins/Sharpen",
    "digikamimageplugins/Shear",
    "digikamimageplugins/Texture",
    "digikamimageplugins/Unsharp",
    "digikamimageplugins/White Balance",
    "digikamimageplugins/Wish for new plugin",
    "docs",
    "docs/Corrections",
    "docs/docs.kde.org",
    "docs/faq",
    "docs/ksgmltools",
    "docs/Missing Content",
    "docs/Screenshots",
    "dolphin",
    "dolphin/bars: filter",
    "dolphin/bars: location",
    "dolphin/bars: status",
    "dolphin/panels: folders",
    "dolphin/panels: information",
    "dolphin/panels: places",
    "dolphin/panels: search",
    "dolphin/panels: terminal",
    "dolphin/plugins: bazaar",
    "dolphin/plugins: dropbox",
    "dolphin/plugins: git",
    "dolphin/plugins: mercurial",
    "dolphin/plugins: svn",
    "dolphin/search",
    "dolphin/split view",
    "dolphin/view-engine: columns mode",
    "dolphin/view-engine: compact mode",
    "dolphin/view-engine: details mode",
    "dolphin/view-engine: general",
    "dolphin/view-engine: icons mode",
    "dolphin/view-engine: tooltip",
    "dragonplayer",
    "drkonqi",
    "drkonqi/backtraceparsing",
    "extra-cmake-modules",
    "filelight",
    "forum.kde.org",
    "frameworks-frameworkintegration",
    "frameworks-kactivities",
    "frameworks-kactivities/fileitemplugin",
    "frameworks-kactivities/kio",
    "frameworks-kactivities/libkactivities",
    "frameworks-kactivities/settings",
    "frameworks-karchive",
    "frameworks-kauth",
    "frameworks-kbookmarks",
    "frameworks-kcmutils",
    "frameworks-kcodecs",
    "frameworks-kcompletion",
    "frameworks-kconfig",
    "frameworks-kconfigwidgets",
    "frameworks-kcoreaddons",
    "frameworks-kcrash",
    "frameworks-kdaemon",
    "frameworks-kdbusaddons",
    "frameworks-kdeclarative",
    "frameworks-kdelibs4support",
    "frameworks-kdesignerplugin",
    "frameworks-kdesu",
    "frameworks-kdewebkit",
    "frameworks-kdnssd",
    "frameworks-kdoctools",
    "frameworks-kemoticons",
    "frameworks-kfileaudiopreview",
    "frameworks-kglobalaccel",
    "frameworks-kguiaddons",
    "frameworks-khtml",
    "frameworks-ki18n",
    "frameworks-kiconthemes",
    "frameworks-kidletime",
    "frameworks-kimageformats",
    "frameworks-kinit",
    "frameworks-kio",
    "frameworks-kitemmodels",
    "frameworks-kitemviews",
    "frameworks-kjobwidgets",
    "frameworks-kjs",
    "frameworks-kjsembed",
    "frameworks-kmediaplayer",
    "frameworks-knewstuff",
    "frameworks-knotifications",
    "frameworks-knotifyconfig",
    "frameworks-kparts",
    "frameworks-kplotting",
    "frameworks-kpty",
    "frameworks-kross",
    "frameworks-kservice",
    "frameworks-ktexteditor",
    "frameworks-ktextwidgets",
    "frameworks-kunitconversion",
    "frameworks-kwallet",
    "frameworks-kwidgetsaddons",
    "frameworks-kwindowsystem",
    "frameworks-kxmlgui",
    "frameworks-kxmlrpcclient",
    "frameworks-modemmanager-qt",
    "frameworks-networkmanager-qt",
    "frameworks-package",
    "frameworks-package/default",
    "frameworks-plasma",
    "frameworks-plasma/components",
    "frameworks-plasma/libplasma",
    "frameworks-plasma/libplasmaquick",
    "frameworks-solid",
    "frameworks-sonnet",
    "frameworks-threadweaver",
    "gcompris",
    "gluon",
    "gluon/gluonaudio",
    "gluon/gluoncreator",
    "gluon/gluonengine",
    "gluon/gluongraphics",
    "gluon/gluoninput",
    "gluon/gluonplayer",
    "Granatier",
    "grantlee",
    "guidance",
    "gwenview",
    "gwenview/importer",
    "headerthemeeditor",
    "HIG",
    "homerun",
    "homerun/applet",
    "homerun/sources",
    "i18n",
    "i18n/af",
    "i18n/bg",
    "i18n/br",
    "i18n/ca",
    "i18n/cs",
    "i18n/cy",
    "i18n/da",
    "i18n/de",
    "i18n/el",
    "i18n/en_GB",
    "i18n/eo",
    "i18n/es",
    "i18n/et",
    "i18n/eu",
    "i18n/fi",
    "i18n/fr",
    "i18n/ga",
    "i18n/gl",
    "i18n/gu",
    "i18n/he",
    "i18n/hr",
    "i18n/hu",
    "i18n/is",
    "i18n/it",
    "i18n/ja",
    "i18n/ko",
    "i18n/lt",
    "i18n/lv",
    "i18n/mk",
    "i18n/nb",
    "i18n/nl",
    "i18n/nn",
    "i18n/oc",
    "i18n/pl",
    "i18n/pt",
    "i18n/pt-BR",
    "i18n/ro",
    "i18n/ru",
    "i18n/sk",
    "i18n/sl",
    "i18n/sr",
    "i18n/sv",
    "i18n/ta",
    "i18n/th",
    "i18n/tr",
    "i18n/uk",
    "i18n/wa",
    "i18n/zh_CN",
    "i18n/zh_TW",
    "jovie",
    "jovie/General",
    "juk",
    "k3b",
    "k3b/Audio Project",
    "k3b/Burning/Hardware",
    "k3b/Copying",
    "k3b/Data Project",
    "k3b/eMovix project",
    "k3b/GUI/Usability",
    "k3b/Image Formats",
    "k3b/K3bSetup",
    "k3b/Mixed Mode Project",
    "k3b/Plugins",
    "k3b/Verfication",
    "k3b/Video CD project",
    "k3b/Video DVD",
    "KAccounts",
    "KAccounts/Daemon",
    "KAccounts/KCM",
    "kaddressbook",
    "kaddressbook/ldap search",
    "kaddressbook/printing",
    "KAddressbook Mobile",
    "kaffeine",
    "kajongg",
    "kalarm",
    "kalarm/Akonadi",
    "kalarm/kalarmd",
    "kalarm/sound",
    "kalcul",
    "kalgebra",
    "kalzium",
    "kalzium/Calculator",
    "kamoso",
    "kanagram",
    "Kannasaver",
    "Kannasaver/General",
    "kapman",
    "kappfinder",
    "kapptemplate",
    "karbon",
    "karbon/opendocument",
    "karbon/usability",
    "kard",
    "kate",
    "kate/application",
    "kate/encoding",
    "kate/folding",
    "kate/indentation",
    "kate/kwrite",
    "kate/part",
    "kate/python plugins",
    "kate/scripting",
    "kate/search",
    "kate/sessions",
    "kate/smart",
    "kate/Snippets Plugin",
    "kate/syntax",
    "kate/Vi Input Mode",
    "katomic",
    "kaudiocreator",
    "kaveau",
    "kbackgammon",
    "KBibTeX",
    "KBibTeX/Compiling/packaging",
    "KBibTeX/General",
    "KBibTeX/Loading/saving files",
    "KBibTeX/Network/online search",
    "KBibTeX/User interface",
    "kblackbox",
    "kblocks",
    "kbounce",
    "kbreakout",
    "kbruch",
    "kcachegrind",
    "kcalc",
    "kcharselect",
    "kcm_grub2",
    "kcm_grub2/General",
    "kcoloredit",
    "kcron",
    "kde",
    "kde/clipboard",
    "kde/dualhead",
    "kde/xinerama",
    "KDE Config Driver Manager",
    "KDE Config Module for Whoopsie",
    "KDE PIM Mobile",
    "kde-cli-tools",
    "kde-gtk-config",
    "kde-windows",
    "kde-windows/buildsystem",
    "kde-windows/installer",
    "kde-windows/network and files",
    "kde-windows/other",
    "kde-windows/porting",
    "kdebugdialog",
    "kdeconnect",
    "kdeconnect/android-application",
    "kdeconnect/common",
    "kdeconnect/kcm",
    "kdeconnect/plasmoid",
    "kded-appmenu",
    "kded-appmenu/export",
    "kded-appmenu/menu popup",
    "kded-appmenu/top menubar",
    "kdelibs",
    "kdelibs/kbugreport",
    "kdelibs/kcertpart",
    "kdelibs/kdecore",
    "kdelibs/kded",
    "kdelibs/kdeinit",
    "kdelibs/kdesasl",
    "kdelibs/kdeui",
    "kdelibs/kdewebkit",
    "kdelibs/kedittoolbar",
    "kdelibs/kimgio",
    "kdelibs/klauncher",
    "kdelibs/klocale",
    "kdelibs/kmdi",
    "kdelibs/knetwork",
    "kdelibs/knewstuff",
    "kdelibs/knotify",
    "kdelibs/kpasswdserver",
    "kdelibs/kshareddatacache",
    "kdelibs/kspell",
    "kdelibs/kstyle",
    "kdelibs/ksycoca",
    "kdelibs/kunitconverter",
    "kdelibs/kwallet",
    "kdelibs/print-dialog",
    "kdelibs/qt",
    "kdelibs/shortcuts",
    "kdemultimedia",
    "kdemultimedia/ffmpegthumbs",
    "kdemultimedia/libkcompactdisc",
    "kdemultimedia/mplayerthumbs",
    "kdenlive",
    "kdenlive/Documentation",
    "kdenlive/Effects & Transitions",
    "kdenlive/Installation",
    "kdenlive/Translation",
    "kdenlive/User Interface",
    "kdenlive/Video Display & Export",
    "kdepasswd",
    "kdepim",
    "kdepim/backupmail",
    "kdepim/importwizard",
    "kdepim/libkdepim",
    "kdepim/libkleo",
    "kdepim/libkpgp",
    "kdepim/messagecomposer",
    "kdepim/messagecore",
    "kdepim/messagelist",
    "kdepim/messagetemplates",
    "kdepim/messageviewer",
    "kdepim/wizards",
    "kdepimlibs",
    "kdepimlibs/akonadi",
    "kdepimlibs/gpgme++",
    "kdepimlibs/kabc",
    "kdepimlibs/kblog",
    "kdepimlibs/kcal",
    "kdepimlibs/kcalcore",
    "kdepimlibs/kholidays",
    "kdepimlibs/kldap",
    "kdepimlibs/kmime",
    "kdepimlibs/kpimidentities",
    "kdepimlibs/kpimtextedit",
    "kdepimlibs/kpimutils",
    "kdepimlibs/mailtransport",
    "kdepimlibs/qgpgme",
    "kdepimlibs/syndication",
    "kdeplasma-addons",
    "kdeplasma-addons/calculator",
    "kdeplasma-addons/converter",
    "kdeplasma-addons/dictionary",
    "kdeplasma-addons/fuzzy-clock",
    "kdeplasma-addons/General",
    "kdeplasma-addons/haenau",
    "kdeplasma-addons/hunyango",
    "kdeplasma-addons/kimpanel-applet",
    "kdeplasma-addons/kimpanel-dataengine",
    "kdeplasma-addons/konsoleprofiles",
    "kdeplasma-addons/notes",
    "kdeplasma-addons/systemloadviewer",
    "kdeplasma-addons/timer",
    "kdesdk-scripts",
    "kdesdk-scripts/cmake",
    "kdesdk-scripts/Miscellaneous",
    "kdesdk-scripts/source_control",
    "kdesrc-build",
    "kdesrc-build/documentation",
    "kdesrc-build/project metadata",
    "kdesrc-build/setup wizard",
    "kdesrc-build/test suite",
    "kdesu",
    "kdesu/kdesu",
    "kdesu/kdesud",
    "kdesvn",
    "kdesvn/General",
    "kdev-clang",
    "kdev-clang/General",
    "kdev-python",
    "kdev-python/Code completion",
    "kdev-python/Documentation data",
    "kdev-python/Language support",
    "kdev-python/User interface",
    "kdev-qmljs",
    "kdev-qmljs/code completion",
    "kdev-qmljs/language support",
    "kdevelop",
    "kdevelop/abbreviation plugin",
    "kdevelop/all build tools",
    "kdevelop/all editors",
    "kdevelop/application templates",
    "kdevelop/astyle",
    "kdevelop/bookmarks part",
    "kdevelop/Build tools: ANT",
    "kdevelop/Build tools: Automake",
    "kdevelop/Build tools: CMake",
    "kdevelop/Build tools: Custom Makefiles",
    "kdevelop/Build tools: QMake",
    "kdevelop/BuildSystem: Custom BuildSystems",
    "kdevelop/Buildtools: Make",
    "kdevelop/code completion",
    "kdevelop/coverage",
    "kdevelop/CPP Debugger",
    "kdevelop/CTags",
    "kdevelop/distpart",
    "kdevelop/doctreeview",
    "kdevelop/documentation viewer",
    "kdevelop/documentview",
    "kdevelop/doxygen integration",
    "kdevelop/file create",
    "kdevelop/file groups",
    "kdevelop/file selector",
    "kdevelop/file tree",
    "kdevelop/ident",
    "kdevelop/kdevelop 2.x (obsolete)",
    "kdevelop/Language Support: Ada",
    "kdevelop/Language Support: CPP",
    "kdevelop/Language Support: Java",
    "kdevelop/Language Support: Pascal",
    "kdevelop/Language Support: Perl",
    "kdevelop/Language Support: PHP",
    "kdevelop/Language Support: Ruby",
    "kdevelop/okteta",
    "kdevelop/Output Views",
    "kdevelop/partexplorer",
    "kdevelop/problem reporter",
    "kdevelop/Profiles",
    "kdevelop/qeditor",
    "kdevelop/Qt Designer Integration",
    "kdevelop/scriptproject",
    "kdevelop/session support",
    "kdevelop/UI: all modes",
    "kdevelop/UI: childframe window",
    "kdevelop/UI: IDEAl",
    "kdevelop/UI: tabbed pages",
    "kdevelop/UI: toplevel window",
    "kdevelop/valgrind integration",
    "kdevelop/VCS: Clearcase",
    "kdevelop/VCS: Perforce",
    "kdevplatform",
    "kdevplatform/appwizard",
    "kdevplatform/classbrowser",
    "kdevplatform/contextbrowser",
    "kdevplatform/cvs",
    "kdevplatform/dashboard",
    "kdevplatform/debugger",
    "kdevplatform/documentswitcher",
    "kdevplatform/dvcs",
    "kdevplatform/editor integration",
    "kdevplatform/filemanager",
    "kdevplatform/git",
    "kdevplatform/grepview",
    "kdevplatform/konsole integration",
    "kdevplatform/language",
    "kdevplatform/mercurial",
    "kdevplatform/openwith",
    "kdevplatform/outputview",
    "kdevplatform/patchreview",
    "kdevplatform/problemreporter",
    "kdevplatform/project",
    "kdevplatform/quickopen",
    "kdevplatform/run support",
    "kdevplatform/session",
    "kdevplatform/shell",
    "kdevplatform/snippet",
    "kdevplatform/sourceformatter",
    "kdevplatform/sublime",
    "kdevplatform/subversion",
    "kdevplatform/templates",
    "kdevplatform/util",
    "kdevplatform/vcs",
    "kdevplatform/veritas",
    "kdf",
    "kdiagram",
    "kdiagram/KChart",
    "kdiagram/KGantt",
    "kdialog",
    "kdiamond",
    "kdiff3",
    "kdiff3/KDiff3Part",
    "kdm",
    "kdm/kdmdesktop",
    "kdm/krootimage",
    "kdots",
    "kdots/default",
    "keditbookmarks",
    "kexi",
    "kexi/Documentation",
    "kexi/Forms",
    "kexi/General",
    "kexi/KexiDB",
    "kexi/Migration/Import/Export",
    "kexi/Queries",
    "kexi/Reports and Printouts",
    "kexi/Scripting",
    "kexi/Tables",
    "kexi/Usability",
    "Keyboard status applet",
    "kfax",
    "kfile",
    "kfile/kfileplacesview",
    "kfile/kpropertiesdialog",
    "kfile/kurlnavigator",
    "kfile-plugins",
    "kfile-plugins/avi",
    "kfile-plugins/exr",
    "kfile-plugins/jpeg",
    "kfile-plugins/mp3",
    "kfile-plugins/mpeg",
    "kfile-plugins/ogg",
    "kfile-plugins/OOo",
    "kfile-plugins/pdf",
    "kfile-plugins/PNG",
    "kfile-plugins/ps",
    "kfile-plugins/wav",
    "kfilereplace",
    "kfind",
    "kfloppy",
    "kfontview",
    "kfourinline",
    "kfritz",
    "kfritz/Call list",
    "kfritz/Call notification",
    "kfritz/Documentation",
    "kfritz/General",
    "kfritz/Phone books",
    "kfritz/Setup",
    "kfritz/Usability",
    "kftpgrabber",
    "kgeography",
    "kget",
    "kget/Core",
    "kget/konqextension",
    "kget/metalink",
    "kget/Multisegkio",
    "kget/plasma widget",
    "kget/torrent",
    "kget/UI",
    "kget/webinterface",
    "kgoldrunner",
    "kgpg",
    "kgrapheditor",
    "kgraphviewer",
    "khangman",
    "khelpcenter",
    "khipu",
    "khipu/core",
    "khotkeys",
    "khotkeys/Voice recognition",
    "kig",
    "kigo",
    "kile",
    "kile/editor",
    "kile/user interface",
    "killbots",
    "kimagemapeditor",
    "kimtoy",
    "kinfocenter",
    "kinfocenter/All KCMs",
    "kinfocenter/Device Viewer",
    "kinfocenter/Energy Information",
    "kinfocenter/IEEE 1394 Device",
    "kinfocenter/Info",
    "kinfocenter/InfoSummary",
    "kinfocenter/KInfoCenter Viewer",
    "kinfocenter/Memory",
    "kinfocenter/Network Interfaces",
    "kinfocenter/OpenGL",
    "kinfocenter/PCI",
    "kinfocenter/Samba",
    "kinfocenter/USB Devices",
    "kio",
    "kio/audiocd",
    "kio/cgi",
    "kio/desktop",
    "kio/devices",
    "kio/file",
    "kio/fish",
    "kio/floppy",
    "kio/ftp",
    "kio/gopher",
    "kio/help",
    "kio/home",
    "kio/http",
    "kio/imap",
    "kio/info",
    "kio/kamera",
    "kio/kfile",
    "kio/kioslave",
    "kio/kssl",
    "kio/man",
    "kio/media",
    "kio/mtp",
    "kio/network",
    "kio/nfs",
    "kio/nntp",
    "kio/pop3",
    "kio/remote",
    "kio/settings",
    "kio/sftp",
    "kio/sieve",
    "kio/smb",
    "kio/smbro",
    "kio/smtp",
    "kio/svn",
    "kio/system",
    "kio/tar",
    "kio/thumbnail",
    "kio/trash",
    "kio/uiserver",
    "kio/webdav",
    "kio/zeroconf",
    "kio/zip",
    "kio-extras",
    "kio-extras/default",
    "kiosk",
    "kiosk/kiosktool",
    "kipiplugins",
    "kipiplugins/AcquireImages",
    "kipiplugins/AdvancedSlideshow",
    "kipiplugins/BatchProcessImages",
    "kipiplugins/Calendar",
    "kipiplugins/DLNAExport",
    "kipiplugins/DngConverter",
    "kipiplugins/DropBox",
    "kipiplugins/ExpoBlending",
    "kipiplugins/Facebook",
    "kipiplugins/FlashExport",
    "kipiplugins/FlickrExport",
    "kipiplugins/GalleryExport",
    "kipiplugins/GoogleDrive",
    "kipiplugins/GPSSync",
    "kipiplugins/HTMLExport",
    "kipiplugins/ImageShackExport",
    "kipiplugins/ImageViewer",
    "kipiplugins/ImgurExport",
    "kipiplugins/IpodExport",
    "kipiplugins/JPEGLossLess",
    "kipiplugins/KIOImportExport",
    "kipiplugins/KMLExport",
    "kipiplugins/MediaWiki",
    "kipiplugins/MetadataEdit",
    "kipiplugins/Panorama",
    "kipiplugins/PhotoLayoutsEditor",
    "kipiplugins/PicasaWeb",
    "kipiplugins/PiwigoExport",
    "kipiplugins/PrintWizard",
    "kipiplugins/RajceExport",
    "kipiplugins/RAWConverter",
    "kipiplugins/RemoveRedEyes",
    "kipiplugins/SendImages",
    "kipiplugins/Shwup",
    "kipiplugins/Smug",
    "kipiplugins/TimeAdjust",
    "kipiplugins/VideoSlideshow",
    "kipiplugins/vkontakte",
    "kipiplugins/Wallpaper",
    "kipiplugins/Wish For New Plugins",
    "kipiplugins/YandexFotki",
    "kiriki",
    "kiten",
    "kjots",
    "KJots Mobile",
    "kjsembed",
    "kjsembed/Core",
    "kjsembed/Docs and examples",
    "kjsembed/Plugins",
    "kjumpingcube",
    "kleopatra",
    "kleopatra/Assuan UI Server",
    "klettres",
    "klickety",
    "klines",
    "klinkstatus",
    "klipper",
    "klipper/plasma-widget",
    "kmag",
    "kmahjongg",
    "KMail Mobile",
    "kmail2",
    "kmail2/commands and actions",
    "kmail2/composer",
    "kmail2/composereditor-ng",
    "kmail2/config dialog",
    "kmail2/contact completion",
    "kmail2/crypto",
    "kmail2/filtering",
    "kmail2/folders",
    "kmail2/MDN",
    "kmail2/message list",
    "kmail2/misc",
    "kmail2/search",
    "kmail2/sieve",
    "kmail2/UI",
    "kmailcvt",
    "kmenuedit",
    "kmid",
    "kmines",
    "kmix",
    "kmix/Backend: OSS4",
    "kmix/Backend: Pulseaudio",
    "kmix/Documentation",
    "kmix/KMix Panel Docking",
    "kmix/Obsolete component. Do NOT use!!! (ex: KMix Panel Applet).",
    "kmix/On Hold / External issue",
    "kmix/On-Screen-Display (OSD)",
    "kmix/QA and Testing",
    "kmix/Soundcard specific",
    "kmix/Visual: Layout and GUI",
    "kmldonkey",
    "kmldonkey/libkmldonkey",
    "kmousetool",
    "kmouth",
    "kmplayer",
    "kmplot",
    "kmtrace",
    "kmymoney",
    "kmymoney/General",
    "kmymoney4",
    "kmymoney4/csvimporter",
    "kmymoney4/database",
    "kmymoney4/file",
    "kmymoney4/onlinebanking",
    "knavalbattle",
    "knemo",
    "knetattach",
    "knetwalk",
    "knights",
    "knipptasch",
    "knode",
    "knotes",
    "kobby",
    "kolf",
    "kollision",
    "kolor-manager",
    "kolor-manager/kolor-manager",
    "kolor-manager/kolor-server",
    "kolourpaint",
    "kolourpaint/general-kde4",
    "kolourpaint/imagelib",
    "kolourpaint/ui",
    "kolourpaint/ui-kde4",
    "kommander",
    "kommander/Kommander editor",
    "kommander/Kommander executor",
    "kompare",
    "kompare/navigationpart",
    "kompare/parser",
    "kompare/viewpart",
    "konqueror",
    "konqueror/bookmarks",
    "konqueror/dirfilterplugin",
    "konqueror/feedplugin",
    "konqueror/file icon view",
    "konqueror/file list view",
    "konqueror/fsview",
    "konqueror/htmlsettingsplugin",
    "konqueror/imagerotation",
    "konqueror/kcookiejar",
    "konqueror/khtml",
    "konqueror/khtml adblock",
    "konqueror/khtml ecma",
    "konqueror/khtml event",
    "konqueror/khtml forms",
    "konqueror/khtml image part",
    "konqueror/khtml parsing",
    "konqueror/khtml part",
    "konqueror/khtml printing",
    "konqueror/khtml renderer",
    "konqueror/khtml svg",
    "konqueror/khtml xml",
    "konqueror/kimgalleryplugin",
    "konqueror/kjava",
    "konqueror/kjs",
    "konqueror/konq-e",
    "konqueror/kuick",
    "konqueror/New Plugin wishes",
    "konqueror/nsplugins",
    "konqueror/nspluginscan",
    "konqueror/nspluginviewer",
    "konqueror/reaktivate",
    "konqueror/rellinks",
    "konqueror/searchbarplugin",
    "konqueror/servicemenus",
    "konqueror/session restore",
    "konqueror/shellcmdplugin",
    "konqueror/sidebar",
    "konqueror/sidebar media player",
    "konqueror/tabbing",
    "konqueror/webarchiverplugin",
    "konquest",
    "konsole",
    "konsole/bookmark",
    "konsole/copy-paste",
    "konsole/emulation",
    "konsole/font",
    "konsole/history",
    "konsole/keyboard",
    "konsole/kpart",
    "konsole/kwrited",
    "konsole/monitoring",
    "konsole/single-process",
    "konsole/split-view",
    "konsole/tabbar",
    "konsolekalendar",
    "kontact",
    "kontact/akregator",
    "kontact/calendar",
    "kontact/contacts",
    "kontact/journal",
    "kontact/ktimetracker",
    "kontact/mail",
    "kontact/new plugin wishes",
    "kontact/news",
    "kontact/newsticker",
    "kontact/notes",
    "kontact/planner summary",
    "kontact/special dates",
    "kontact/summary",
    "kontact/todo",
    "konversation",
    "konversation/dcc",
    "konversation/documentation",
    "konversation/encryption",
    "konversation/ignore",
    "konversation/inputline",
    "konversation/ircview",
    "konversation/logging",
    "konversation/notifications",
    "konversation/protocol",
    "konversation/systemcontacts",
    "konversation/tabcompletion",
    "konversation/upnp",
    "kooka",
    "kooka/libkscan",
    "kopete",
    "kopete/Add Contact Wizard",
    "kopete/Addressbook integration",
    "kopete/Alias Plugin",
    "kopete/Audio/Video Plugin",
    "kopete/Auto-Away Plugin",
    "kopete/Autoreplace plugin",
    "kopete/Bonjour Plugin",
    "kopete/Bookmarks plugin",
    "kopete/Chat Window",
    "kopete/Chatwindow Styles",
    "kopete/Connection Status Plugin",
    "kopete/Contact list",
    "kopete/Contact Notes Plugin",
    "kopete/Cryptography Plugin",
    "kopete/DBus",
    "kopete/DCOP Interface",
    "kopete/Facebook Plugin",
    "kopete/Gadu-Gadu Plugin",
    "kopete/History Plugin",
    "kopete/ICQ and AIM Plugins",
    "kopete/Importer plugin",
    "kopete/IRC Plugin",
    "kopete/Jabber Plugin",
    "kopete/Latex Plugin",
    "kopete/libkopete",
    "kopete/Lotus Sametime Plugin",
    "kopete/Main Application",
    "kopete/Meanwhile plugin",
    "kopete/MSN Plugin",
    "kopete/New plugin wishes",
    "kopete/Notifications",
    "kopete/Novell GroupWise Messenger Plugin",
    "kopete/Now Listening Plugin",
    "kopete/OTR Plugin",
    "kopete/Pipes Plugin",
    "kopete/Privacy Plugin",
    "kopete/QQ Plugin",
    "kopete/Skype Plugin",
    "kopete/SMS Plugin",
    "kopete/SpellCheck Plugin",
    "kopete/Statistics plugin",
    "kopete/Testbed Plugin",
    "kopete/Texteffect Plugin",
    "kopete/Translator Plugin",
    "kopete/Web Presence Plugin",
    "kopete/WinPopup Plugin",
    "kopete/WLM Plugin",
    "kopete/Yahoo Plugin",
    "korgac",
    "korganizer",
    "korganizer/agendaview (weekview)",
    "korganizer/embedded",
    "korganizer/exchangeplugin",
    "korganizer/groupware",
    "korganizer/html export",
    "korganizer/import/export",
    "korganizer/incidence editors",
    "korganizer/incidence viewer",
    "korganizer/invitations",
    "korganizer/journalview",
    "korganizer/monthview",
    "korganizer/otherviews",
    "korganizer/printing",
    "korganizer/recurrence",
    "korganizer/reminder daemon (korgac)",
    "korganizer/timezones",
    "korganizer/todoview",
    "KOrganizer Mobile",
    "KOrganizer Mobile/calendar",
    "KOrganizer Mobile/tasks",
    "kpat",
    "kpat/solver",
    "kpeople",
    "kpeople/PersonsModel",
    "kpeople/PersonsPresenceModel",
    "kpeople/ResourceWatcher",
    "kphotoalbum",
    "kphotoalbum/Android client",
    "kphotoalbum/Annotation Dialog",
    "kphotoalbum/Backend",
    "kphotoalbum/Browser",
    "kphotoalbum/Datebar",
    "kphotoalbum/EXIF viewer/search",
    "kphotoalbum/HTML generator",
    "kphotoalbum/Import/Export",
    "kphotoalbum/SQL backend",
    "kphotoalbum/Thumbnail Viewer",
    "kphotoalbum/Viewer",
    "kphotoalbum/XML backend",
    "kplayer",
    "kppp",
    "kqtquickcharts",
    "krazy",
    "krdc",
    "krdc/NX",
    "krdc/RDP",
    "krdc/VNC",
    "krecipes",
    "krecord",
    "kreenshot-editor",
    "kregexpeditor",
    "kremotecontrol",
    "kremotecontrol/daemon",
    "kremotecontrol/settings",
    "kremotecontrol/tray",
    "kresources",
    "kresources/birthdays",
    "kresources/blogging",
    "kresources/bugzilla",
    "kresources/egroupware",
    "kresources/exchange",
    "kresources/featureplan",
    "kresources/framework",
    "kresources/groupdav",
    "kresources/groupwise",
    "kresources/imap",
    "kresources/ldap",
    "kresources/local",
    "kresources/newexchange",
    "kresources/remote",
    "kresources/SLOX",
    "kreversi",
    "krfb",
    "krita",
    "krita/adjustment layers",
    "krita/Brush engine",
    "krita/Color models",
    "krita/color selectors",
    "krita/Dockers",
    "krita/Documentation",
    "krita/File formats",
    "krita/Filters",
    "krita/G'Mic for Krita",
    "krita/krita gemini",
    "krita/krita sketch",
    "krita/Layer Stack",
    "krita/tablet support",
    "krita/Tile manager",
    "krita/Tools",
    "krita/transform",
    "krita/usability",
    "krita/Vector Objects and Tools",
    "kronometer",
    "kruler",
    "krunner",
    "krunner/audioplayercontrol",
    "krunner/bookmarks",
    "krunner/calculator",
    "krunner/converter",
    "krunner/events",
    "krunner/filesearch",
    "krunner/locations",
    "krunner/places",
    "krunner/quicksand",
    "krunner/solid",
    "krunner/spellchecker",
    "krunner/webshortcuts",
    "krunner/windows",
    "krusader",
    "krusader/disk-usage",
    "krusader/krarc",
    "krusader/krviewer",
    "krusader/net-connection",
    "krusader/search",
    "krusader/shortcuts",
    "krusader/synchronize",
    "ksayit",
    "kscd",
    "KScreen",
    "KScreen/common",
    "KScreen/kcm",
    "KScreen/kded",
    "KScreen/libkscreen",
    "KScreen/Plasma Applet",
    "ksecretsservice",
    "ksecretsservice/Client library",
    "ksecretsservice/Daemon",
    "ksecretsservice/ksecretssync",
    "kshisen",
    "ksirk",
    "ksirkskineditor",
    "ksmserver",
    "ksmserver/lockscreen",
    "ksmserver/ui",
    "ksnapshot",
    "ksnapshot/send-to menu",
    "kspaceduel",
    "ksplash",
    "KSquares",
    "ksshaskpass",
    "kst",
    "kst/datasources",
    "kst/documentation",
    "kst/elog extension",
    "kst/equations",
    "kst/i18n",
    "kst/packaging",
    "kst/plotting",
    "kst/plugins",
    "kst/scripting",
    "kst/ui",
    "kst/view objects",
    "kstars",
    "kstart",
    "ksudoku",
    "ksvg2",
    "ksysguard",
    "ksysguard/ksysguard",
    "ksysguard/ksysguardd",
    "ksysguard/libksysguard",
    "ksysguard/Plasmoid / Applet",
    "ksysguard/Process Controller - krunner part",
    "KSystemLog",
    "ksystraycmd",
    "kte-collaborative",
    "kte-collaborative/General",
    "kte-collaborative/KIO slave",
    "kte-collaborative/Telepathy integration",
    "kte-collaborative/Text buffer",
    "kteatime",
    "ktimer",
    "ktimetracker",
    "ktimetracker/reporting",
    "ktnef",
    "ktorrent",
    "ktouch",
    "ktouchpadenabler",
    "ktouchpadenabler/General",
    "ktron",
    "kttt",
    "ktuberling",
    "kturtle",
    "kubrick",
    "Kubuntu Debug Installer",
    "Kubuntu Notifications Helper",
    "kuiviewer",
    "kuser",
    "kverbos",
    "kvkbd",
    "kvpnc",
    "kwalletmanager",
    "kwayland",
    "kwebkitpart",
    "kwikdisk",
    "kwin",
    "kwin/activities",
    "kwin/appmenu",
    "kwin/aurorae",
    "kwin/colorcorrection",
    "kwin/compatibility",
    "kwin/compositing",
    "kwin/core",
    "kwin/decorations",
    "kwin/effects-tabbox",
    "kwin/effects-various",
    "kwin/effects-window-management",
    "kwin/egl",
    "kwin/glx",
    "kwin/kdecorations",
    "kwin/multihead",
    "kwin/rules",
    "kwin/scene-opengl",
    "kwin/scene-xrender",
    "kwin/scripting",
    "kwin/tabbox",
    "kwin/tiling",
    "kwin/window-tabbing",
    "kwin/xinerama",
    "kwin/xrandr",
    "kwordquiz",
    "kwrited",
    "kxkb",
    "kxsldbg",
    "kxsldbg/kxsldbg",
    "kxsldbg/xsldbg",
    "KXStitch",
    "KXStitch/pattern-libraries",
    "KXStitch/schemes",
    "KXStitch/symbol-libraries",
    "LabPlot2",
    "LabPlot2/backend",
    "LabPlot2/frontend",
    "libalkimia",
    "libalkimia/General",
    "libechonest",
    "libkcddb",
    "libkdeedu",
    "libkdeedu/keduvocdocument",
    "libkdegames",
    "libkdegames/kgamerenderer",
    "libkeduvocdocument",
    "libkgapi",
    "libkgapi/blogger",
    "libkgapi/calendar",
    "libkgapi/contacts",
    "libkgapi/drive",
    "libkgapi/General",
    "libkgapi/latitude",
    "libkgapi/static maps",
    "libkgapi/tasks",
    "libksane",
    "LibKubuntu",
    "libkvkontakte",
    "libmediawiki",
    "libqgit2",
    "libqinfinity",
    "lightdm",
    "lightdm/config",
    "lightdm/greeter",
    "lightdm/theme-classic",
    "lightdm/theme-userbar",
    "lokalize",
    "lokalize/editor",
    "lokalize/glossary",
    "lokalize/project management",
    "lokalize/translation memory",
    "lskat",
    "magazynier",
    "mancala",
    "Mangonel",
    "Mangonel/mangonel",
    "marble",
    "marble/data",
    "marble/plasmoid",
    "marble/wallpaper",
    "marble/website",
    "massif-visualizer",
    "massif-visualizer/callgraph",
    "massif-visualizer/massif-parser",
    "massif-visualizer/memorychart",
    "muon",
    "muon/discover",
    "muon/installer",
    "muon/libqapt",
    "muon/misc",
    "muon/muon",
    "muon/notifier",
    "muon/qapt-batch",
    "muon/qapt-deb-installer",
    "muon/qaptworker",
    "muon/updater",
    "Necessitas",
    "Necessitas/Android Qt4",
    "Necessitas/Android Qt4 Mobility",
    "Necessitas/Android Qt4 WebKit",
    "Necessitas/Android QtCreator",
    "Necessitas/Ministro",
    "Necessitas/SDK Installer",
    "Necessitas/Web infrastructure",
    "okteta",
    "okteta/Structures Tool",
    "okular",
    "okular/CHM backend",
    "okular/Comicbook backend",
    "okular/DjVu backend",
    "okular/DVI backend",
    "okular/EPub backend",
    "okular/Fax backend",
    "okular/Image backend components",
    "okular/mobipocket backend",
    "okular/New backend wishes",
    "okular/ODT backend",
    "okular/PDF backend",
    "okular/printing",
    "okular/PS backend",
    "okular/TIFF backend",
    "okular/XPS backend",
    "Oxygen",
    "Oxygen/fonts",
    "Oxygen/gtk2-engine",
    "Oxygen/gtk3-engine",
    "Oxygen/icons",
    "Oxygen/QtQuickControls",
    "Oxygen/sound",
    "Oxygen/style",
    "Oxygen/win deco",
    "Pairs",
    "Pairs/editor",
    "palapeli",
    "palapeli/libpala",
    "palapeli/slicers",
    "parley",
    "parley/editor",
    "parley/scripts",
    "partitionmanager",
    "paste.kde.org",
    "Phonon",
    "Phonon/avKode backend",
    "Phonon/Directshow",
    "Phonon/frontend",
    "Phonon/KDE platform plugin",
    "Phonon/kded module for audio device listing",
    "Phonon/Mplayer backend",
    "Phonon/NMM backend",
    "Phonon/Pulsesupport",
    "Phonon/settings",
    "Phonon/Xine backend",
    "phonon-backend-gstreamer",
    "phonon-backend-vlc",
    "picmi",
    "pimsettingexporter",
    "Planet KDE",
    "Planet KDE/feeds",
    "Plasma SDK",
    "Plasma SDK/cuttlefish",
    "Plasma SDK/editor",
    "Plasma SDK/engineexplorer",
    "Plasma SDK/General",
    "Plasma SDK/kconfigxteditor",
    "Plasma SDK/konsolepreviewer",
    "Plasma SDK/metadataeditor",
    "Plasma SDK/plasma-remote-helper-widgets",
    "Plasma SDK/plasmathemeexplorer",
    "Plasma SDK/plasmawallpaperviewer",
    "Plasma SDK/plasmoidviewer",
    "Plasma SDK/publisher",
    "Plasma SDK/remoteinstaller",
    "Plasma Workspace Wallpapers",
    "plasma-mediacenter",
    "plasma-mediacenter/BrowsingBackends",
    "plasma-mediacenter/General",
    "plasma-mediacenter/Libs",
    "plasma-mediacenter/MediaBrowser",
    "plasma-mediacenter/MediaController",
    "plasma-mediacenter/MediaPlayer",
    "plasma-mediacenter/Playlist",
    "plasma-mediacenter/Shell",
    "plasma-nm",
    "plasma-nm/applet",
    "plasma-nm/editor",
    "plasma4",
    "plasma4/activities",
    "plasma4/containment-desktop",
    "plasma4/containment-panel",
    "plasma4/dashboard",
    "plasma4/dataengines",
    "plasma4/desktop",
    "plasma4/groupingdesktop",
    "plasma4/mouse actions",
    "plasma4/multihead",
    "plasma4/multiscreen",
    "plasma4/notifications",
    "plasma4/panel",
    "plasma4/plasma-netbook",
    "plasma4/qml-components",
    "plasma4/remotewidgets",
    "plasma4/screensaver overlay",
    "plasma4/scriptengines",
    "plasma4/visuals",
    "plasma4/wallpaper-image",
    "plasma4/wallpaper-marble",
    "plasma4/wallpaper-virus",
    "plasma4/wallpaper-weather",
    "plasma4/widget explorer",
    "plasma4/widget-activitybar",
    "plasma4/widget-analogclock",
    "plasma4/widget-battery",
    "plasma4/widget-bouncyball",
    "plasma4/widget-bubblemon",
    "plasma4/widget-calculator",
    "plasma4/widget-clock",
    "plasma4/widget-colorpicker",
    "plasma4/widget-comic",
    "plasma4/widget-current-application-control",
    "plasma4/widget-devicenotifier",
    "plasma4/widget-dictionary",
    "plasma4/widget-fifteenpuzzle",
    "plasma4/widget-filewatcher",
    "plasma4/widget-folderview",
    "plasma4/widget-frame",
    "plasma4/widget-fuzzyclock",
    "plasma4/widget-ggadgets",
    "plasma4/widget-icontasks",
    "plasma4/widget-incomingmessage",
    "plasma4/widget-kickoff",
    "plasma4/widget-konsoleprofiles",
    "plasma4/widget-lancelot",
    "plasma4/widget-luna",
    "plasma4/widget-mediaplayer",
    "plasma4/widget-microblogging",
    "plasma4/widget-misc",
    "plasma4/widget-networkmonitor",
    "plasma4/widget-news",
    "plasma4/widget-notes",
    "plasma4/widget-nowplaying",
    "plasma4/widget-opendesktop",
    "plasma4/widget-osx",
    "plasma4/widget-pager",
    "plasma4/widget-paste",
    "plasma4/widget-pastebin",
    "plasma4/widget-quicklaunch",
    "plasma4/widget-rememberthemilk",
    "plasma4/widget-rssnow",
    "plasma4/widget-shelf",
    "plasma4/widget-systemloadviewer",
    "plasma4/widget-systemmonitor",
    "plasma4/widget-systemtray",
    "plasma4/widget-taskbar",
    "plasma4/widget-timer",
    "plasma4/widget-trashcan",
    "plasma4/widget-weather",
    "plasma4/widget-webbrowser",
    "plasma4/widget-webslice",
    "plasma4/widget-windowlist",
    "plasma4/widget-worldclock",
    "plasmashell",
    "plasmashell/Activity Switcher",
    "plasmashell/Analogue Clock",
    "plasmashell/Application Launcher (Kickoff)",
    "plasmashell/Application Menu (Kicker)",
    "plasmashell/Battery Monitor",
    "plasmashell/Calendar",
    "plasmashell/DataEngines",
    "plasmashell/Desktop Containment",
    "plasmashell/Desktop Dashboard",
    "plasmashell/Device Notifier",
    "plasmashell/Digital Clock",
    "plasmashell/Folder",
    "plasmashell/Icons-only Task Manager",
    "plasmashell/Image Wallpaper",
    "plasmashell/Look & Feel package",
    "plasmashell/Media Controller",
    "plasmashell/Milou",
    "plasmashell/Multi-screen support",
    "plasmashell/Notifications",
    "plasmashell/Pager",
    "plasmashell/Panel",
    "plasmashell/System Tray",
    "plasmashell/Task Manager",
    "plasmashell/Theme - Breeze",
    "plasmashell/Widget Explorer",
    "policykit-kde-agent-1",
    "policykit-kde-agent-1/kcm_auth",
    "policykit-kde-agent-1/manager",
    "policykit-kde-agent-1/polkit-kde-authentication-agent-1",
    "Powerdevil",
    "Predicate",
    "Predicate/Driver: MySQL",
    "Predicate/Driver: PostgreSQL",
    "Predicate/Driver: SQLite",
    "Predicate/General",
    "Predicate/Migration",
    "print-manager",
    "qaccessibilityclient",
    "qca",
    "QmlWeb",
    "QmlWeb/QML-Engine",
    "QmlWeb/QML-Parser",
    "QmlWeb/QtQuick",
    "qtatspi",
    "QtCurve",
    "QtCurve/gtk2",
    "QtCurve/gtk3",
    "QtCurve/qt4",
    "QtCurve/qt5",
    "rekonq",
    "rekonq/security",
    "rekonq/sessions",
    "rekonq/user interface",
    "rekonq/web app",
    "rekonq/web content",
    "Rocs",
    "Rocs/script engine",
    "Rocs/UI",
    "Rocs/visual graph editor",
    "season.kde.org",
    "showfoto",
    "sieveeditor",
    "simon",
    "simon/afaras",
    "simon/julius",
    "simon/ksimond",
    "simon/sam",
    "simon/simon",
    "simon/simond",
    "simon/simonoid",
    "simon/ssc",
    "simon/sscd",
    "simon-tools",
    "simon-tools/panic",
    "simon-tools/simon-touch",
    "simon-tools/simone",
    "simon-tools/simonskype",
    "simon-tools/simonstatus",
    "simon-tools/speechcal",
    "Skanlite",
    "skrooge",
    "smaragd",
    "step",
    "step/stepcore",
    "storageservicemanager",
    "superkaramba",
    "sweeper",
    "SymbolEditor",
    "Systemd KCM",
    "systemsettings",
    "systemsettings/kcmshell",
    "systemsettings/kcm_accessibility",
    "systemsettings/kcm_audiocd",
    "systemsettings/kcm_autostart",
    "systemsettings/kcm_bell",
    "systemsettings/kcm_clock",
    "systemsettings/kcm_colors",
    "systemsettings/kcm_componentchooser",
    "systemsettings/kcm_desktoppath",
    "systemsettings/kcm_desktopsearch",
    "systemsettings/kcm_desktopthemedetails",
    "systemsettings/kcm_deviceautomounter",
    "systemsettings/kcm_emoticons",
    "systemsettings/kcm_energy",
    "systemsettings/kcm_fileshare",
    "systemsettings/kcm_filetypes",
    "systemsettings/kcm_fontinst",
    "systemsettings/kcm_fonts",
    "systemsettings/kcm_formats",
    "systemsettings/kcm_gtk",
    "systemsettings/kcm_icons",
    "systemsettings/kcm_joystick",
    "systemsettings/kcm_kamera",
    "systemsettings/kcm_kded",
    "systemsettings/kcm_kdm",
    "systemsettings/kcm_kdnssd",
    "systemsettings/kcm_keyboard",
    "systemsettings/kcm_keyboard_layout",
    "systemsettings/kcm_keys",
    "systemsettings/kcm_kgamma",
    "systemsettings/kcm_khotkeys",
    "systemsettings/kcm_ksmserver",
    "systemsettings/kcm_ksplashthememgr",
    "systemsettings/kcm_kthememanage",
    "systemsettings/kcm_language",
    "systemsettings/kcm_launch",
    "systemsettings/kcm_mouse",
    "systemsettings/kcm_netpref",
    "systemsettings/kcm_notify",
    "systemsettings/kcm_phonon",
    "systemsettings/kcm_proxy",
    "systemsettings/kcm_randr",
    "systemsettings/kcm_samba",
    "systemsettings/kcm_screensaver",
    "systemsettings/kcm_sddm",
    "systemsettings/kcm_solid-actions",
    "systemsettings/kcm_ssl",
    "systemsettings/kcm_standard_actions",
    "systemsettings/kcm_style",
    "systemsettings/kcm_useraccount",
    "systemsettings/krdb",
    "systemsettings/treeview",
    "taglib",
    "telepathy",
    "telepathy/accounts-kcm",
    "telepathy/approver",
    "telepathy/auth-handler",
    "telepathy/call-ui",
    "telepathy/chat-plasmoid",
    "telepathy/common-internals",
    "telepathy/contact-applet",
    "telepathy/contact-runner",
    "telepathy/contactlist",
    "telepathy/contactlist-applet",
    "telepathy/debugger",
    "telepathy/documentation",
    "telepathy/filetransfer",
    "telepathy/kded-module",
    "telepathy/kopete-migrator",
    "telepathy/kopete-protocol-telepathy",
    "telepathy/KPeople plugins",
    "telepathy/kwhiteboard",
    "telepathy/launcher-kded",
    "telepathy/libktelepathy",
    "telepathy/log-viewer",
    "telepathy/nepomuk-service",
    "telepathy/ontology",
    "telepathy/OTR",
    "telepathy/presence-applet",
    "telepathy/presence-dataengine",
    "telepathy/send-file",
    "telepathy/telepathy-logger-qt",
    "telepathy/testlib",
    "telepathy/text-ui",
    "telepathy/text-ui-message-filters",
    "tellico",
    "Touchpad-KCM",
    "Touchpad-KCM/daemon",
    "Touchpad-KCM/kcm",
    "Touchpad-KCM/plasma-applet",
    "trojita",
    "trojita/Core",
    "trojita/Desktop GUI",
    "trojita/Harmattan",
    "trojita/IMAP",
    "trojita/Message Composer",
    "trojita/Other",
    "trojita/SMTP",
    "trojita/Ubuntu",
    "umbrello",
    "umbrello/documentation",
    "unknown",
    "user-manager",
    "user-manager/kcontrol module",
    "valgrind",
    "valgrind/bbv",
    "valgrind/cachegrind",
    "valgrind/callgrind",
    "valgrind/dhat",
    "valgrind/drd",
    "valgrind/helgrind",
    "valgrind/massif",
    "valgrind/memcheck",
    "valgrind/sgcheck",
    "valgrind/vex",
    "valkyrie",
    "wacomtablet",
    "wicd-client-kde",
    "workout",
    "www.kde.org",
    "www.kde.org/jointhegame.kde.org",
    "www.kde.org/sprints.kde.org",
    "yakuake",
    "zanshin",
nullptr };
